---
title: "Jaringan Sains Psikologi Indonesia"
format: html
toc: false
---

## Selamat Datang!

Jaringan Sains Psikologi Indonesia merupakan entitas yang diinisiasi dengan tiga misi utama, yaitu:

1. Meningkatkan kesadaran di antara peneliti dan praktisi psikologi tentang pentingnya menjamin kualitas dan kredibilitas penelitian dasar dan terapan
2. Mendukung peningkatan kapasitas peneliti dan praktisi psikologi di Indonesia untuk melakukan penelitian yang cermat secara ilmiah
3. Mendorong adanya konsensus tentang arah dan masa depan perkembangan keilmuan psikologi di Indonesia

Kami membuka kesempatan kepada rekan-rekan yang tertarik untuk menerima informasi lebih lanjut tentang gerakan ini dengan cara mengisi **pernyataan ketertarikan** [<i class="fas fa-external-link-alt"></i>](https://docs.google.com/forms/d/e/1FAIpQLSd9v1fd-wWGbLsMscCKisa67KX2tM5hzKnbpFmr2Pggi_BNVQ/viewform?usp=dialog).

Silakan kontak kami melalui <i class="fa-regular fa-envelope"></i> di [jaspsi.indonesia@gmail.com](mailto:jaspsi.indonesia@gmail.com).